version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_KEY_STORE_FILE: /opt/keycloak/conf/tls-ssl-commcert.p12
      KC_HTTPS_KEY_STORE_PASSWORD: 123456
      KC_LOG_LEVEL: INFO
    command: ["start-dev"]
    volumes:
      - ./target/keycloak-eid-identity-provider.jar:/opt/keycloak/providers/keycloak-eid-identity-provider.jar
      - ./src/main/resources/keys/tls-ssl-commcert.p12:/opt/keycloak/conf/tls-ssl-commcert.p12
    ports:
      - "8443:8443"
